# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/as2872/vivado_projects/zynq_spi_emio_diff/zynq_spi_emio_diff.cache/wt [current_project]
set_property parent.project_path /home/as2872/vivado_projects/zynq_spi_emio_diff/zynq_spi_emio_diff.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:microzed_7010:part0:1.1 [current_project]
add_files /home/as2872/vivado_projects/zynq_spi_emio_diff/zynq_spi_emio_diff.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/as2872/vivado_projects/zynq_spi_emio_diff/zynq_spi_emio_diff.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/as2872/vivado_projects/zynq_spi_emio_diff/zynq_spi_emio_diff.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_0_4/design_1_util_ds_buf_0_4_board.xdc]
set_property used_in_implementation false [get_files -all /home/as2872/vivado_projects/zynq_spi_emio_diff/zynq_spi_emio_diff.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_0_0/design_1_util_ds_buf_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/as2872/vivado_projects/zynq_spi_emio_diff/zynq_spi_emio_diff.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_0_1/design_1_util_ds_buf_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/as2872/vivado_projects/zynq_spi_emio_diff/zynq_spi_emio_diff.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_0_2/design_1_util_ds_buf_0_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/as2872/vivado_projects/zynq_spi_emio_diff/zynq_spi_emio_diff.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_4_1/design_1_util_ds_buf_4_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/as2872/vivado_projects/zynq_spi_emio_diff/zynq_spi_emio_diff.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files /home/as2872/vivado_projects/zynq_spi_emio_diff/zynq_spi_emio_diff.srcs/sources_1/bd/design_1/design_1.bd]

read_verilog -library xil_defaultlib /home/as2872/vivado_projects/zynq_spi_emio_diff/zynq_spi_emio_diff.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/as2872/vivado_projects/zynq_spi_emio_diff/zynq_spi_emio_diff.srcs/constrs_1/new/pin_assgns.xdc
set_property used_in_implementation false [get_files /home/as2872/vivado_projects/zynq_spi_emio_diff/zynq_spi_emio_diff.srcs/constrs_1/new/pin_assgns.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef design_1_wrapper.dcp

catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
