# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin_assgns.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0}]

# IP: bd/design_1/ip/design_1_util_ds_buf_0_4/design_1_util_ds_buf_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_0_4 || ORIG_REF_NAME==design_1_util_ds_buf_0_4}]

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0}]

# IP: bd/design_1/ip/design_1_xlconstant_0_1/design_1_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_1 || ORIG_REF_NAME==design_1_xlconstant_0_1}]

# IP: bd/design_1/ip/design_1_util_ds_buf_0_0/design_1_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_0_0 || ORIG_REF_NAME==design_1_util_ds_buf_0_0}]

# IP: bd/design_1/ip/design_1_util_ds_buf_0_1/design_1_util_ds_buf_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_0_1 || ORIG_REF_NAME==design_1_util_ds_buf_0_1}]

# IP: bd/design_1/ip/design_1_util_ds_buf_0_2/design_1_util_ds_buf_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_0_2 || ORIG_REF_NAME==design_1_util_ds_buf_0_2}]

# IP: bd/design_1/ip/design_1_util_ds_buf_4_1/design_1_util_ds_buf_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_4_1 || ORIG_REF_NAME==design_1_util_ds_buf_4_1}]

# XDC: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_util_ds_buf_0_4/design_1_util_ds_buf_0_4_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_0_4 || ORIG_REF_NAME==design_1_util_ds_buf_0_4}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_util_ds_buf_0_0/design_1_util_ds_buf_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_0_0 || ORIG_REF_NAME==design_1_util_ds_buf_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_util_ds_buf_0_1/design_1_util_ds_buf_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_0_1 || ORIG_REF_NAME==design_1_util_ds_buf_0_1}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_util_ds_buf_0_2/design_1_util_ds_buf_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_0_2 || ORIG_REF_NAME==design_1_util_ds_buf_0_2}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_util_ds_buf_4_1/design_1_util_ds_buf_4_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_4_1 || ORIG_REF_NAME==design_1_util_ds_buf_4_1}] {/U0 }]/U0 ]]

# XDC: bd/design_1/design_1_ooc.xdc
